#!/usr/bin/env python3
r"""Generate the two views of the object ledger. Never hand-edit the outputs.

  objects/LEDGER.md                      -- the human table (status per object)
  book/latex/preamble/objects-generated.tex -- LaTeX macros the book uses:
        \ObjStatus{id}   -> proved | computed | open | ...
        \ObjScope{id}    -> the declared subset / cost model
        \ObjEvidence{id} -> one line naming the artifact and whether it was checked
        \ObjTitle{id}

The book therefore cannot claim a status the ledger does not hold: a chapter
that says "proved" for an open object shows the ledger's word, not the author's.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OBJ = ROOT / "objects"
PARTS = {
    1: "Part I -- Constructing an instruction set",
    2: "Part II -- Reading x86-64 and RISC-V",
    3: "Part III -- Proving claims about programs",
    4: "Part IV -- Synthesis and boundary",
}

def tex_escape(s: str) -> str:
    return (s.replace("\\", "\\textbackslash{}").replace("&", "\\&").replace("%", "\\%")
             .replace("$", "\\$").replace("#", "\\#").replace("_", "\\_").replace("{", "\\{").replace("}", "\\}")
             .replace("~", "\\textasciitilde{}").replace("^", "\\textasciicircum{}"))

def key(id_: str) -> str:
    # LaTeX macro-safe key: letters only
    out = []
    for ch in id_:
        if ch.isalpha(): out.append(ch)
        elif ch.isdigit(): out.append("abcdefghij"[int(ch)])
        else: out.append("x")
    return "".join(out)

def main():
    recs = [json.loads(p.read_text()) for p in sorted(OBJ.glob("*.json"))]
    recs.sort(key=lambda r: (r["part"], r["id"]))
    # ---- LEDGER.md
    lines = ["# Object ledger", "", "> **Generated by `scripts/gen_ledger.py`. Do not edit.** One row per object in `objects/*.json`;",
             "> every value is read from the record. `checked` means `scripts/check_objects.py --run` re-executes",
             "> a checker whose exit status depends on the finding; `replay-only` means the artifact replays but no",
             "> independent certificate exists; `not-checked` is an honest citation.", ""]
    from collections import Counter
    c = Counter(r["epistemic_status"] for r in recs); ck = Counter(e["check_status"] for r in recs for e in r["evidence"])
    lines += [f"- Objects: **{len(recs)}** -- " + ", ".join(f"`{k}` {v}" for k, v in sorted(c.items())),
              f"- Evidence rows: **{sum(ck.values())}** -- " + (", ".join(f"`{k}` {v}" for k, v in sorted(ck.items())) or "none"), ""]
    for part in sorted(set(r["part"] for r in recs)):
        lines += [f"## {PARTS.get(part, part)}", "", "| ID | Kind | Title | Status | External | Scope | Evidence |", "|---|---|---|---|---|---|---|"]
        for r in recs:
            if r["part"] != part: continue
            ev = "<br>".join(f"`{e['kind']}` / `{e['trust_class']}`: {e['check_status']}" for e in r["evidence"]) or "--"
            lines.append(f"| [`{r['id']}`]({r['id']}.json) | {r['kind']} | {r['title']} | `{r['epistemic_status']}` | `{r.get('external_status','--')}` | {r.get('scope','--')} | {ev} |")
        lines.append("")
    (OBJ / "LEDGER.md").write_text("\n".join(lines))
    # ---- LaTeX macros
    tex = ["% GENERATED by scripts/gen_ledger.py from objects/*.json -- do not edit.",
           "% Provides \\ObjStatus, \\ObjScope, \\ObjEvidence, \\ObjTitle keyed by object id.",
           "\\makeatletter"]
    for r in recs:
        k = key(r["id"])
        ev = "; ".join(f"{e['kind']} / {e['trust_class']} ({e['check_status']})" for e in r["evidence"]) or "no evidence recorded"
        tex += [f"\\@namedef{{objstatus@{k}}}{{{tex_escape(r['epistemic_status'])}}}",
                f"\\@namedef{{objscope@{k}}}{{{tex_escape(r.get('scope','') or '--')}}}",
                f"\\@namedef{{objevidence@{k}}}{{{tex_escape(ev)}}}",
                f"\\@namedef{{objtitle@{k}}}{{{tex_escape(r['title'])}}}"]
    tex += ["\\makeatother"]
    (ROOT / "book" / "latex" / "preamble" / "objects-generated.tex").write_text("\n".join(tex) + "\n")
    # key table for the preamble helper (id -> key), as a sidecar the preamble reads
    (ROOT / "book" / "latex" / "preamble" / "objects-keys.tex").write_text(
        "% GENERATED: object id -> macro key\n" +
        "\n".join(f"\\expandafter\\def\\csname objkey@{r['id']}\\endcsname{{{key(r['id'])}}}" for r in recs) + "\n")
    print(f"ledger: {len(recs)} objects -> objects/LEDGER.md, book/latex/preamble/objects-generated.tex")

if __name__ == "__main__":
    main()
